base_images:
  cli-ocm:
    name: cli-ocm
    namespace: ci
    tag: latest
  rosa-aws-cli:
    name: rosa-aws-cli
    namespace: ci
    tag: latest
build_root:
  image_stream_tag:
    name: ci-tools-build-root
    namespace: ci
    tag: latest
images:
- dockerfile_path: prow/Dockerfile
  to: ocp-qe-perfscale-ci-loaded-upgrade-414to415
promotion:
  to:
  - namespace: ci
    tag: latest
releases:
  latest:
    release:
      channel: candidate
      version: "4.15"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: perfscale-rosa-multiaz-120nodes-stage-loaded-upgrade415
  cron: 0 8 1,15 * *
  steps:
    allow_skip_on_success: true
    cluster_profile: aws-perfscale-qe
    env:
      CHANNEL_GROUP: candidate
      CHURN: "false"
      COMPUTE_MACHINE_TYPE: m5.xlarge
      ENABLE_AUTOSCALING: "false"
      GC: "false"
      HOSTED_CP: "false"
      IDP_TIMEOUT: "1200"
      IF_INTERMEDIATE_UPGRADE: "false"
      ITERATION_MULTIPLIER_ENV: "9"
      MULTI_AZ: "true"
      OCM_LOGIN_ENV: staging
      OPENSHIFT_VERSION: "4.14"
      READY_WAIT_TIMEOUT: 30m
      REGION: us-west-2
      REPLICAS: "120"
      USER_COUNT: "30"
    test:
    - ref: ipi-install-rbac
    - ref: openshift-cluster-bot-rbac
    - chain: openshift-qe-cluster-density-v2
    - chain: openshift-qe-rosa-loaded-upgrade
    workflow: rosa-aws-sts
  timeout: 8h0m0s
- as: perfscale-rosa-multiaz-180nodes-stage-loaded-upgrade415
  cron: 0 8 2,16 * *
  steps:
    allow_skip_on_success: true
    cluster_profile: aws-perfscale-qe
    env:
      CHANNEL_GROUP: candidate
      CHURN: "false"
      COMPUTE_MACHINE_TYPE: m5.xlarge
      ENABLE_AUTOSCALING: "false"
      GC: "false"
      HOSTED_CP: "false"
      IDP_TIMEOUT: "1200"
      IF_INTERMEDIATE_UPGRADE: "false"
      ITERATION_MULTIPLIER_ENV: "9"
      MULTI_AZ: "true"
      OCM_LOGIN_ENV: staging
      OPENSHIFT_VERSION: "4.14"
      READY_WAIT_TIMEOUT: 30m
      REGION: us-west-2
      REPLICAS: "180"
      USER_COUNT: "30"
    test:
    - ref: ipi-install-rbac
    - ref: openshift-cluster-bot-rbac
    - chain: openshift-qe-cluster-density-v2
    - chain: openshift-qe-rosa-loaded-upgrade
    workflow: rosa-aws-sts
  timeout: 8h0m0s
- as: perfscale-rosa-multiaz-249nodes-stage-loaded-upgrade415
  cron: 0 8 3,17 * *
  steps:
    allow_skip_on_success: true
    cluster_profile: aws-perfscale-qe
    env:
      CHANNEL_GROUP: candidate
      CHURN: "false"
      COMPUTE_MACHINE_TYPE: m5.xlarge
      ENABLE_AUTOSCALING: "false"
      GC: "false"
      HOSTED_CP: "false"
      IDP_TIMEOUT: "1200"
      IF_INTERMEDIATE_UPGRADE: "false"
      ITERATION_MULTIPLIER_ENV: "9"
      MULTI_AZ: "true"
      OCM_LOGIN_ENV: staging
      OPENSHIFT_VERSION: "4.14"
      READY_WAIT_TIMEOUT: 30m
      REGION: us-west-2
      REPLICAS: "249"
      USER_COUNT: "30"
    test:
    - ref: ipi-install-rbac
    - ref: openshift-cluster-bot-rbac
    - chain: openshift-qe-cluster-density-v2
    - chain: openshift-qe-rosa-loaded-upgrade
    workflow: rosa-aws-sts
  timeout: 8h0m0s
zz_generated_metadata:
  branch: main
  org: openshift-qe
  repo: ocp-qe-perfscale-ci
  variant: rosa-4.15-candidate-x86-loaded-upgrade-from-4.14
