build_root:
  image_stream_tag:
    name: ci-tools-build-root
    namespace: ci
    tag: latest
images:
- dockerfile_path: prow/Dockerfile
  to: ocp-qe-perfscale-ci-rosa-4.14-nightly
promotion:
  namespace: ci
  tag: latest
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.14"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: perfscale-rosa-multiaz-control-plane-120nodes-periodic
  cron: 0 12 * * 6
  steps:
    cluster_profile: aws-perfscale
    env:
      CHANNEL_GROUP: nightly
      COMPUTE_MACHINE_TYPE: m5.xlarge
      ENABLE_AUTOSCALING: "false"
      MULTI_AZ: "true"
      OPENSHIFT_VERSION: "4.14"
      REPLICAS: "120"
    test:
    - chain: openshift-qe-control-plane
    workflow: rosa-aws-sts
  timeout: 6h0m0s
- always_run: false
  as: perfscale-rosa-hcp-multiaz-control-plane-120nodes
  steps:
    cluster_profile: aws-perfscale
    env:
      CHANNEL_GROUP: nightly
      COMPUTE_MACHINE_TYPE: m5.xlarge
      DISABLE_WORKLOAD_MONITORING: "false"
      ENABLE_AUTOSCALING: "false"
      HOSTED_CP: "true"
      MULTI_AZ: "true"
      OPENSHIFT_VERSION: "4.14"
      REPLICAS: "120"
      ZONES_COUNT: "3"
    test:
    - chain: openshift-qe-control-plane
    workflow: rosa-aws-sts-hypershift
- always_run: false
  as: perfscale-rosa-hcp-multiaz-control-plane-252nodes
  steps:
    cluster_profile: aws-perfscale
    env:
      CHANNEL_GROUP: nightly
      COMPUTE_MACHINE_TYPE: m5.xlarge
      DISABLE_WORKLOAD_MONITORING: "false"
      ENABLE_AUTOSCALING: "false"
      HOSTED_CP: "true"
      MULTI_AZ: "true"
      OPENSHIFT_VERSION: "4.14"
      REPLICAS: "252"
      ZONES_COUNT: "3"
    test:
    - chain: openshift-qe-control-plane
    workflow: rosa-aws-sts-hypershift
zz_generated_metadata:
  branch: main
  org: openshift-qe
  repo: ocp-qe-perfscale-ci
  variant: rosa-4.14-nightly-x86
